<?php
/* @var \Codilar\HelloWorld\Block\Hello $block */
/* @var \Codilar\HelloWorld\ViewModel\Search $viewModel */
?>
<label><?= __("First") ?></label>
<h1><?= $block->getText() ?></h1>
<label><?= __("Second")?></label>
<h1><?= $block->getUser() ?></h1>
<label><?= __("Third")?></label>
<h1><?= $block->getPosts() ?></h1>
<label><?= __("Fourth")?></label>
<!--<p>Type scu<Br>-->
<!--    <textarea name="scu"></textarea>-->
<!--</p>-->
<!--<p>-->
<!--    <input type="submit" value="Отправить">-->
<!--</p>-->
<?php
$productData = $block->getData();
$viewModel = $block->getData('view_model');
$viewModel->HelloWorld();
?>
<label name="<?= $viewModel->HelloWorld(); ?>">123</label>
<div class="col-sm-8">
    <form method="GET" action="<?= $block->getUrl('smartautobrand/search/search'); ?>" id="search" role="form" name="search" enctype="multipart/form-data" data-mage-init='{"validation":{"rules": {"field-2": {"required":true}}}}'>
        <div class="form-group">
            <h2>Form</h2>
        </div>
        <div class="form-group">
            <label class="control-label"><span><?= $block->escapeHtml('Type scu') ?></span></label>
            <input id="sku" name="sku" type="text" class="form-control" data-validate='{"required":true}'>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="Submit" id="search-btn" class="action submit primary"'>
                    <span>Submit</span>
                </button>
            </div>
        </div>
    </form>
</div>
