<?php
/* @var \JS\Ajax\Block\Search $block */
?>
<div class="col-sm-8">
    <form method="POST" action="<?= $this->getUrl('search'); ?>" id="search" role="form" name="search" enctype="multipart/form-data" data-mage-init='{"validation":{"rules": {"field-2": {"required":true}}}}'>
        <div class="form-group">
            <h2>Form</h2>
        </div>
        <div class="form-group">
            <label class="control-label"><span><?= $block->escapeHtml('Type scu') ?></span></label>
            <input id="sku" name="sku" type="text" class="form-control" data-validate='{"required":true}'>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="Submit" id="search-btn" class="action submit primary" data-mage-init='{"search":{}}'>
                    <span>Submit</span>
                </button>
            </div>
        </div>
    </form>
</div>
