<div class="header-top">
    <div class="header-top__left">
        <div class="language">
            <select class="header-top__left-language">
                <option>English</option>
                <option>Brazilian</option>
            </select>
        </div>
        <div class="currency">
            <select class="header-top__left-currency">
                <option>$ - USD</option>
                <option>€ - EUR</option>
            </select>
        </div>
        <div class="login-or-register">
            <a href="/">Login</a> 
            <span>or</span>
            <a href="/">Register</a>
        </div>
    
    </div>
    <div class="header-top__right">
        <div class="phone-number">
            <a href="tel: 012-323-584-98">012-323-584-98</a>
        </div>
        <div class="store-location">
            <span>Store location</span>
        </div>
    </div>
</div>