<div id="weather" data-bind="scope: 'weather'">

    <!-- ko template: getTemplate() --><!-- /ko -->

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "weather": {
                            "component": "TestModule_Weather/js/view/weatherRequest",
                            "template":  "TestModule_Weather/weather"
                        }
                    }
                }
            }
        }
    </script>
</div>